### PR TITLE
checking in Pruthvi

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by thejmazz** [comment]
If you reopen this I'll merge. I've also sent you an invite to the team so once that is accepted you can accept the pull yourself or just leave this be and commit to the main branch.

**Comment by ghost** [comment]
Oh thanks! I was not sure how fork worked so I just tried to mess around
with a little bit.
So I was just wondering if I fork a repository and then there are changes
made to the master rep does that affect the forked rep? and what if I make
changes to my version of the project, can I not merge them
since the master is different?

**Comment by thejmazz** [comment]
If you fork a repo from `bigorg/project` it will copy that repository into `username/project`. These are completely separate entities. You can play with `username/project` as much as you want and no one will even notice. Generally, to contrib to a project you don't belong to, one would fork it, clone their copy, create a branch:

``` bash
git checkout -b fixBug5
```

Work there, make some commits, push to their copy. Then go to the official project and create a pull request. We won't need to do this here since I've invited everyone to be team members of the organization. Thus you can just clone n' push. So I would recommend doing that instead of pulling this.

**Comment by ghost** [comment]
Alright that explains a lot. Thanks!

**Pull request closed without merging**
